main: fun.fifu.nekokecore.zxbskyworld.Main
version: 1.0
name: ZxbSkyWorld
author: NekokeCore
commands:
    s:
      description: "回到自己的岛"
      usage: /s <玩家名>
    goto:
      description: "去某个岛"
      usage: /goto <SkyLoc>
