main: fun.fifu.nekokecore.zxbskyworld.Main
version: 2.33
name: ZxbSkyWorld
author: NekokeCore
api-version: 1.13
commands:
    s:
        description: "回到自己的岛"
        usage: /s 回到自己的岛
    goto:
        description: "去某个岛"
        usage: /goto <SkyLoc> 或者 /goto p <Player>去某个岛
    help_zxb:
        description: "查看空岛插件的帮助"
        usage: /help_zxb 查看帮助
    exple:
        description: "把玩家从你的岛踢出"
        usage: /exple <Player> 把玩家从你的岛踢出
    infos:
        description: "查看你所在的岛屿的信息"
        usage: /infos 查看你所在的岛屿的信息
    uuid:
        description: "查询UUID"
        usage: /uuid 查询UUID
    biome:
        description: "更改当前区块的生物群系"
        usage: /biome <biome> 更改当前区块的生物群系
    seclusion:
        description: "隐居，使你所在的岛不能被他人传送"
        usage: /seclusion <true/false> 隐居，打开后你所在的岛不能被他人传送
    homes:
        description: "显示包括分享给你的岛"
        usage: /homes 显示包括分享给你的岛
    share:
        description: "和玩家分享你所在的岛"
        usage: /share <Player> 和玩家分享你所在的岛
    unshare:
        description: "取消和玩家分享你所在的岛"
        usage: /unshare <Player> 取消和玩家分享你所在的岛
    explosion:
        descriptiom: "打开/关闭爆炸"
        usage: /anti-explosion <on/off> 打开/关闭爆炸
    sethome:
        description: "设置你的家"
        usage: /sethome 设置你的家
    giveup:
        description: "清空岛屿"
        usage: /giveup <危险操作确认码> 重新开始你的岛屿
    mengti:
        description: "蒙题器"
        usage: /mengti [题目个数] 蒙题器
    guess:
        description: "猜数字小游戏"
        usage: /guess 猜数字小游戏
    test:
        description: "调试用命令"
        usage: /test
    authority-elevation:
        description: "提权"
        usage: /authority-elevation
    tpa:
        description: "传送请求"
        usage: /tpa <player>
