main: fun.fifu.nekokecore.zxbskyworld.Main
version: 1.2
name: ZxbSkyWorld
author: NekokeCore
commands:
    s:
      description: "回到自己的岛"
      usage: /s <玩家名>
    goto:
      description: "去某个岛"
      usage: /goto <SkyLoc>
    help:
      description: "帮助"
      usage: /help
    exple:
      description: "把玩家从你的岛踢出"
      usage: /exple <Player>
    infos:
      description: "查看你所在的岛屿的信息"
      usage: /infos
    uuid:
      description: "查询UUID"
      usage: /uuid
    biome:
      description: "更改当前岛屿的生物群系"
      usage: /biome <biome>
